export enum constants {
    RETURN = "RETURN",
    SETERRORRS = "SETERRORRS",
    TOGGALE = "TOGGALE",
    CLEARSTATE = "CLEARSTATE",
    NEXT = "NEXT",
    SETPERSONALDATE = "SETPERSONALDATE", 
    SKILLS = "SKILLS"
}